export const copy = {
  zh: {
    nav: { featured: "精選", categories: "分類", all: "全部作品" },
    activeLabel: "在線",
    localeToggle: "EN",
    eyebrow: "PUBLIC / PRIVATE WORK INDEX",
    headline: "Michael Product",
    headlineAccent: "Lab",
    intro:
      "產品型全端作品，橫跨 AI、金融與工具系統。重點不是 repo 數量，而是每個工具解決的問題、系統如何串接，以及最後交付出來的畫面。",
    primaryAction: "看精選作品",
    secondaryAction: "瀏覽全部",
    featured: "精選產品",
    featuredIntro: "先看我日常真的在用的 Telegram 工作中樞，再往下看金融、AI、資料和工具產品。",
    categories: "用產品線瀏覽",
    categoryStory:
      "這些專案不是照 repo 名稱排，而是按使用情境整理：Telegram 指令、KOL 掃描、NotebookLM、金融工具和資料產品各自放在該看的位置。",
    all: "全部",
    allProjects: "全部作品",
    projectsCount: "個案例",
    problem: "設計初衷",
    workflow: "怎麼運作",
    commandOutputs: "指令會得到什麼",
    evidence: "實際輸出",
    created: "建立",
    updated: "更新",
    stack: "技術",
    openDemo: "Demo",
    openSource: "GitHub",
    close: "關閉",
    noSource: "這是內部或私人作品，這裡只放產品脈絡與截圖。",
    footer:
      "有些作品是內部工具或客戶案例，只放截圖和功能摘要。需要看更細的實作，再另外打開。",
    statsPv: "總瀏覽量",
    statsActive: "線上人數",
    views: "預覽次數",
    challenge: "關鍵突破與技術挑戰",
    impact: "實質成效與指標",
    engineeringPillars: "工程設計重點 (Engineering Pillars)",
    pillarObservability: "觀測與容錯 (Observability)",
    pillarCaching: "快取與配額 (Caching & Quota)",
    pillarSecurity: "安全性與認證 (Security)",
    pillarReproducibility: "可重現性與測試 (Reproducibility)",
  },
  en: {
    nav: { featured: "Featured", categories: "Categories", all: "All Work" },
    activeLabel: "Online",
    localeToggle: "繁中",
    eyebrow: "PUBLIC / PRIVATE WORK INDEX",
    headline: "Michael Product",
    headlineAccent: "Lab",
    intro:
      "Product-minded full-stack work across AI, finance, and utility systems. The focus is not repository count, but the problem solved, the system behind it, and the shipped result.",
    primaryAction: "View featured",
    secondaryAction: "Browse all",
    featured: "Featured products",
    featuredIntro:
      "The Telegram operations hub comes first because I actually use it every day. Finance, AI, data, and utility products follow below.",
    categories: "Browse by product line",
    categoryStory:
      "The projects are grouped by use case, not by repo name: Telegram commands, KOL scanning, NotebookLM handoff, finance tools, and data products each get their own context.",
    all: "All",
    allProjects: "All projects",
    projectsCount: "cases",
    problem: "Background",
    workflow: "How it works",
    commandOutputs: "Command outcomes",
    evidence: "Real output",
    created: "Created",
    updated: "Updated",
    stack: "Stack",
    openDemo: "Demo",
    openSource: "GitHub",
    close: "Close",
    noSource: "This is internal or private work, so this page only shows product context and screenshots.",
    footer:
      "Some projects are internal tools or client work, so I only show screenshots and short notes here. Deeper implementation details can be opened case by case.",
    statsPv: "Total Visits",
    statsActive: "Online Users",
    views: "Views",
    challenge: "Key Challenge & Breakthrough",
    impact: "Impact & Metrics",
    engineeringPillars: "Engineering & Robustness Pillars",
    pillarObservability: "Observability & Fail-safe",
    pillarCaching: "Caching & API Limits",
    pillarSecurity: "Security & Webhook Auth",
    pillarReproducibility: "Reproducibility & Mocking",
  },
} as const;

export type PortfolioCopy = (typeof copy)[keyof typeof copy];
