export const copy = {
  zh: {
    nav: ["精選", "分類", "全部作品"],
    eyebrow: "PRODUCT LAB",
    headlineA: "把點子",
    headlineB: "變成",
    headlineC: "實用工具",
    intro:
      "這裡收集了我開發的開源和私有專案。我習慣把每個 repo 當作一個真正的產品來整理：分析它解決了什麼痛點、系統是怎麼串接的，以及實際的產出畫面。",
    primaryAction: "看精選作品",
    secondaryAction: "瀏覽全部",
    featured: "精選產品",
    featuredIntro: "最常用的 Telegram 工作中樞放在第一位，後面再看金融、AI、資料和工具產品。",
    categories: "用產品線瀏覽",
    categoryStory:
      "把 Telegram 指令、KOL 掃描、NotebookLM 分析和金融決策工具放在一起展示，比單純條列 GitHub 倉庫，更能呈現我做過的事。",
    all: "全部",
    allProjects: "全部作品",
    projectsCount: "個案例",
    problem: "設計初衷",
    workflow: "怎麼運作",
    commandOutputs: "指令會得到什麼",
    evidence: "實際輸出",
    created: "建立",
    updated: "更新",
    stack: "技術",
    openDemo: "Demo",
    openSource: "GitHub",
    close: "關閉",
    noSource: "這是內部或私人作品，所以這裡只展示產品脈絡與截圖。",
    footer:
      "部分作品是內部工具或客戶案例，因此只展示產品截圖與功能摘要。需要看更細的實作，再另外打開就好。",
    statsPv: "總瀏覽量",
    statsActive: "線上人數",
    views: "預覽次數",
    challenge: "關鍵突破與技術挑戰",
    impact: "實質成效與指標",
    engineeringPillars: "工程強健性設計 (Engineering Pillars)",
    pillarObservability: "觀測與容錯 (Observability)",
    pillarCaching: "快取與配額 (Caching & Quota)",
    pillarSecurity: "安全性與認證 (Security)",
    pillarReproducibility: "可重現性與測試 (Reproducibility)",
  },
  en: {
    nav: ["Featured", "Categories", "All Work"],
    eyebrow: "PRODUCT LAB",
    headlineA: "Turning ideas",
    headlineB: "into",
    headlineC: "useful tools",
    intro:
      "A product-driven portfolio that translates open-source and private repositories into commercial use cases, showcasing clear problem analysis, system workflows, and real-world outcomes.",
    primaryAction: "View featured",
    secondaryAction: "Browse all",
    featured: "Featured products",
    featuredIntro:
      "The Telegram operations hub comes first because it is the product I use most, followed by finance, AI, data, and utility work.",
    categories: "Browse by product line",
    categoryStory:
      "Telegram commands, KOL scanning, NotebookLM handoff, financial intelligence, data research, and product utilities make more sense as a product lab than as a raw repo list.",
    all: "All",
    allProjects: "All projects",
    projectsCount: "cases",
    problem: "Background",
    workflow: "How it works",
    commandOutputs: "Command outcomes",
    evidence: "Real output",
    created: "Created",
    updated: "Updated",
    stack: "Stack",
    openDemo: "Demo",
    openSource: "GitHub",
    close: "Close",
    noSource: "This is internal or private work, so the portfolio shows product context and screenshots instead of source.",
    footer:
      "Some projects are internal tools or client-facing work, so I show product context and screenshots instead of source links. Deeper implementation details can be opened case by case.",
    statsPv: "Total Visits",
    statsActive: "Online Users",
    views: "Views",
    challenge: "Key Challenge & Breakthrough",
    impact: "Impact & Metrics",
    engineeringPillars: "Engineering & Robustness Pillars",
    pillarObservability: "Observability & Fail-safe",
    pillarCaching: "Caching & API Limits",
    pillarSecurity: "Security & Webhook Auth",
    pillarReproducibility: "Reproducibility & Mocking",
  },
} as const;

export type PortfolioCopy = (typeof copy)[keyof typeof copy];
