export const copy = {
  zh: {
    nav: { featured: "案例", all: "作品索引", github: "GitHub" },
    activeLabel: "在線",
    localeToggle: "EN",
    eyebrow: "INDEPENDENT PRODUCT ENGINEER / TAIWAN",
    headline: "把複雜流程，",
    headlineAccent: "做成可用產品。",
    intro:
      "我設計、開發並持續營運 AI 自動化、金融情報與內部工具。這裡先呈現三個有實際 Demo 的完整案例，再提供所有作品的索引。",
    primaryAction: "看三個案例",
    secondaryAction: "GitHub Profile",
    featured: "三個案例",
    featuredIntro: "不是截圖牆。每個案例都說明產品用途、實際功能與可以直接打開的 Demo。",
    caseStudy: "查看案例",
    liveDemo: "開啟 Demo",
    archiveIntro: "完整作品依時間與產品線整理；往下滑會自動載入下一批。",
    categories: "用產品線瀏覽",
    categoryStory:
      "這些專案不是照 repo 名稱排，而是按使用情境整理：Telegram 指令、KOL 掃描、NotebookLM、金融工具和資料產品各自放在該看的位置。",
    all: "全部",
    allProjects: "全部作品",
    projectsCount: "個案例",
    demoCases: "個有 Demo 的強案例",
    sortLabel: "時間排序",
    sortUpdated: "最近更新",
    sortNewest: "最新建立",
    sortOldest: "最早建立",
    showing: "目前顯示",
    of: "共",
    noProjects: "這個分類目前沒有作品。",
    backToPortfolio: "返回作品集",
    problem: "設計初衷",
    workflow: "怎麼運作",
    commandOutputs: "指令會得到什麼",
    evidence: "實際輸出",
    created: "建立",
    updated: "更新",
    stack: "技術",
    openDemo: "Demo",
    openSource: "GitHub",
    close: "關閉",
    noSource: "這是內部或私人作品，這裡只放產品脈絡與截圖。",
    footer: "有些作品是內部工具或私人案例，只公開產品脈絡與畫面。公開原始碼與更多實驗可以在 GitHub 查看。",
    footerTitle: "從問題出發，交付可以運作的系統。",
    footerAction: "查看 GitHub Profile",
    statsPv: "總瀏覽量",
    statsActive: "線上人數",
    views: "預覽次數",
    challenge: "關鍵突破與技術挑戰",
    impact: "實質成效與指標",
    engineeringPillars: "工程設計重點 (Engineering Pillars)",
    pillarObservability: "觀測與容錯 (Observability)",
    pillarCaching: "快取與配額 (Caching & Quota)",
    pillarSecurity: "安全性與認證 (Security)",
    pillarReproducibility: "可重現性與測試 (Reproducibility)",
  },
  en: {
    nav: { featured: "Cases", all: "Work Index", github: "GitHub" },
    activeLabel: "Online",
    localeToggle: "繁中",
    eyebrow: "INDEPENDENT PRODUCT ENGINEER / TAIWAN",
    headline: "Complex workflows,",
    headlineAccent: "shipped as useful products.",
    intro:
      "I design, build, and operate AI automation, financial intelligence, and internal tools. Start with three working cases, then browse the complete project index.",
    primaryAction: "View three cases",
    secondaryAction: "GitHub Profile",
    featured: "Selected cases",
    featuredIntro: "Not a wall of screenshots. Each case explains the product, its working features, and a Demo you can open.",
    caseStudy: "Read case study",
    liveDemo: "Open live demo",
    archiveIntro: "The complete body of work, sorted by time and product line. More entries load as you scroll.",
    categories: "Browse by product line",
    categoryStory:
      "The projects are grouped by use case, not by repo name: Telegram commands, KOL scanning, NotebookLM handoff, finance tools, and data products each get their own context.",
    all: "All",
    allProjects: "All projects",
    projectsCount: "cases",
    demoCases: "strong cases with demos",
    sortLabel: "Sort by time",
    sortUpdated: "Recently updated",
    sortNewest: "Newest created",
    sortOldest: "Oldest created",
    showing: "Showing",
    of: "of",
    noProjects: "No projects in this category yet.",
    backToPortfolio: "Back to portfolio",
    problem: "Background",
    workflow: "How it works",
    commandOutputs: "Command outcomes",
    evidence: "Real output",
    created: "Created",
    updated: "Updated",
    stack: "Stack",
    openDemo: "Demo",
    openSource: "GitHub",
    close: "Close",
    noSource: "This is internal or private work, so this page only shows product context and screenshots.",
    footer: "Some work is internal or private, so only product context and screenshots are public. Open-source work and more experiments live on GitHub.",
    footerTitle: "Start with a problem. Ship a system that works.",
    footerAction: "View GitHub Profile",
    statsPv: "Total Visits",
    statsActive: "Online Users",
    views: "Views",
    challenge: "Key Challenge & Breakthrough",
    impact: "Impact & Metrics",
    engineeringPillars: "Engineering & Robustness Pillars",
    pillarObservability: "Observability & Fail-safe",
    pillarCaching: "Caching & API Limits",
    pillarSecurity: "Security & Webhook Auth",
    pillarReproducibility: "Reproducibility & Mocking",
  },
} as const;

export type PortfolioCopy = (typeof copy)[keyof typeof copy];
